name: discretize-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.20
  - scipy>=1.8
  - cython>=0.29
  - setuptools_scm
  - pymatsolver>=0.1.2
  - matplotlib
  - jupyter
  - sphinx
  - sphinx-gallery>=0.1.13
  - pydata-sphinx-theme
  - numpydoc>=1.5
  - pillow
  - sympy
  - wheel
  - pytest
  - pytest-cov
  - twine
  - vtk
  - pyvista
  - pip
  - omf
  - graphviz
  # Linters and checkers
  - black==23.1.0
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-docstrings
