name: discretize-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.20
  - scipy>=1.8
  - cython>=0.29
  - setuptools_scm
  - pymatsolver>=0.1.2
  - matplotlib
  - jupyter
  - sphinx
  - sphinx-gallery>=0.1.13
  - sphinx-toolbox
  - sphinxcontrib-apidoc
  - pydata-sphinx-theme
  - numpydoc>=1.5
  - pillow
  - sympy
  - wheel
  - pytest
  - pytest-cov
  - twine
  - vtk
  - pyvista
  - pip
  - omf
  - graphviz
