name: discretize-test
channels:
  - conda-forge
dependencies:
  - numpy>=1.22.4
  - scipy>=1.8
  # optionals
  - vtk
  - pyvista
  - omf
  - matplotlib
  # documentation
  - sphinx
  - pydata-sphinx-theme==0.13.3
  - sphinx-gallery>=0.1.13
  - numpydoc>=1.5
  - jupyter
  - graphviz
  - pymatsolver>=0.1.2
  - pillow
  # testing
  - sympy
  - pytest
  - coverage
  # Building
  - pip
  - meson-python>=0.14.0
  - meson
  - ninja
  - build
  - cython>=0.29.35
  - setuptools_scm
  # Distribute
  - twine
  - wheel
  # Linters and checkers
  - black==23.1.0
  - flake8==6.0.0
  - flake8-bugbear
  - flake8-builtins
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-docstrings
