jobs:
- job:
  displayName: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      win-Python36:
        python.version: '3.6'
      win-Python37:
        python.version: '3.7'
      win-Python38:
        python.version: '3.8'
  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda create --yes --quiet -c conda-forge --name test python=$(python.version) numpy scipy matplotlib cython vtk properties vectormath pyvista pymatsolver pip
    displayName: Create Anaconda environment

  - script: |
      call activate test
      pip install -r requirements_dev.txt
      pip install pytest-azurepipelines
    displayName: Install other requirements

  - script: |
      call activate test
      pip install -e .
    displayName: Build

  - script: |
      call activate test
      pytest tests/base tests/cyl tests/tree -v -s
    displayName: 'Running tests'
