jobs:
- job:
  displayName: Windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      win-Python37:
        python.version: '3.7'
      win-Python38:
        python.version: '3.8'
      win-Python39:
        python.version: '3.9'
  steps:

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      call activate base
      conda install --yes -c conda-forge mamba
    displayName: Install mamba

  - script: |
      call activate base
      mamba create --yes -c conda-forge --name test python=$(python.version) numpy scipy matplotlib cython vtk pyvista pymatsolver pytest "mkl>=2022.1"
    displayName: Create Anaconda environment

  - script: |
      call activate test
      pip install -r requirements_dev.txt
      pip install pytest-azurepipelines
    displayName: Install other requirements

  - script: |
      call activate test
      pip install -e .
    displayName: Build

  - script: |
      call activate test
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Running tests'
